language: node_js
env:
  - TARGET=test
node_js:
  - '6'
  - '8'
matrix:
  include:
    - name: Lint
      node_js: '8'
      env:
        - TARGET=lint
    - name: Coverage
      node_js: '8'
      env:
        - TARGET=coverage
script: npm run $TARGET
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
